name: 02 - Eventos

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'  # Ejecuta cada día a medianoche (modifica según tus necesidades)
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: ShowTrigger
        run: echo "Workflow triggered by: ${{ github.event_name }}"